### ISSUE TITLE
Automate releasing documentation

### ISSUE THREAD

**Issue by mniewrzal** [storj/uplink-c#12]
Would be nice to automatically generate/deploy a new version of documentation after each release.

**Comment by mniewrzal** [comment]
@Erikvv could you add more details how we can do this?

**Comment by Erikvv** [comment]
High level:

- Make sure jenkins builds the latest tag when tagging, doesn't seem like it currently does anything with tags.
- Set the tag in https://github.com/storj/uplink-c/blob/12b6f4001345522c1df43309e7eac215be5b6236/docs/Doxyfile#L41 (for CI replace with environment variable)
- run ./docs/generate.sh
- commit and push the branch gh-pages from directory ./docs/gh-pages

Note: we currently only host documentation for one tag, which would have to be the latest. I was looking at processing the Doxygen XML output with Breath+Sphinx to support this and maybe other improvements.

**Comment by egonelbre** [comment]
Note, it might be easier to do with github actions.

You can setup a github action something like:
```
name: Build with Hugo

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      // -- install tools --
      // -- generate docs --

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
```

Adjust the `publish_dir` as needed.
